AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  LFOwner:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./lambda-functions
      Handler: lf_owner.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/grant_access'
            Method: post
      Policies:
        - CloudWatchLogsFullAccess
        - AmazonRekognitionFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSNSFullAccess

  Passcodes:
    Type: AWS::DynamoDB::Table
    # Specify the composite key here
    Properties:
      TableName: cc-smart-door-passcodes
      AttributeDefinitions:
        - AttributeName: phone_number
          AttributeType: S
      KeySchema:
        - AttributeName: phone_number
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Visitors:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cc-smart-door-visitors
      AttributeDefinitions:
        - AttributeName: faceId
          AttributeType: S
      KeySchema:
        - AttributeName: faceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  VisitorsInfo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cc-smart-door-visitors-info
      AttributeDefinitions:
        - AttributeName: phone_number
          AttributeType: S
      KeySchema:
        - AttributeName: phone_number
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5      

  LFVisitor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./lambda-functions
      Handler: lf_visitor.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/gain_access'
            Method: post
      Policies:
        - CloudWatchLogsFullAccess
        - AmazonDynamoDBFullAccess

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
